name: dog_training_ai
version: 1.0.0+1
description: >-
  Application mobile de dressage canin assistée par IA (Flutter + Firebase + API YOLO)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_auth: ^5.6.0
  google_sign_in: ^6.1.5
  fl_chart: ^1.0.0
  permission_handler: ^12.0.0+1
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true 