name: dog_training_ai
version: 1.0.0+1
description: >-
  Application mobile de dressage canin assistée par IA (Flutter + API YOLO)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  permission_handler: ^11.1.0
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true 